name: Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/projects/download_gost_bot 
          git pull
          docker stop gptishka
          docker rm $(docker container ls --filter 'status=exited')
          docker rmi metravod/download_gost_bot
          docker build -t metravod/download_gost_bot:latest .
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          docker run -d metravod/download_gost_bot:latest
