name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-demo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: fifsky/ssh-action@master
        with:
          host: $ {{ secrets.VPS_HOST }}
          user: $ {{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_VPS }}
      - run: cd your-app-folder && python3 -m invoke deploy-demo-app-to-server
